# Generated by Django 3.2.8 on 2021-11-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_user_order_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
