# Generated by Django 3.2.8 on 2021-11-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
