# Generated by Django 3.2.8 on 2021-11-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='book_borrowed',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
