# Generated by Django 3.2.8 on 2021-12-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='temp_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
