# Generated by Django 3.2.8 on 2021-12-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20211206_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='temp_number',
            new_name='temp_number2',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='user',
        ),
    ]
