# Generated by Django 3.2.8 on 2021-12-06 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20211206_0131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='collection',
        ),
    ]
