# Generated by Django 3.2.8 on 2021-11-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField(max_length=2000)),
                ('date', models.DateTimeField()),
                ('author', models.CharField(max_length=30)),
                ('isavailable', models.BooleanField()),
            ],
        ),
    ]
