# Generated by Django 4.0 on 2021-12-22 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_img', models.ImageField(default='book.jpg', upload_to='book_pics')),
                ('title', models.CharField(max_length=50)),
                ('title_small', models.CharField(max_length=30)),
                ('description_small', models.TextField(max_length=700)),
                ('description', models.TextField(max_length=10000)),
                ('year', models.DateField()),
                ('isavailable', models.BooleanField(default=True)),
                ('quantity', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('part', models.IntegerField()),
                ('age', models.IntegerField()),
                ('ausleihtage', models.IntegerField(default=30)),
                ('language', models.CharField(max_length=20)),
                ('preview', models.CharField(default=0, max_length=200)),
                ('totalorders', models.IntegerField(default=0)),
                ('book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.author')),
                ('genre', models.ManyToManyField(to='books.Category')),
            ],
        ),
    ]
