# Generated by Django 3.2.8 on 2021-11-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_img', models.ImageField(default='book.jpg', upload_to='book_pics')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=2000)),
                ('year', models.DateTimeField()),
                ('Book_author', models.CharField(max_length=30)),
                ('isavailable', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('genre', models.CharField(max_length=12)),
                ('pages', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
