# Generated by Django 3.2.8 on 2021-11-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20211125_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Book_author',
            new_name='book_author',
        ),
    ]
