# Generated by Django 3.2.8 on 2021-11-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_articles_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='body',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date',
        ),
    ]
