# Generated by Django 3.2.8 on 2021-11-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_book_author_book_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description_small',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
