# Generated by Django 3.2.8 on 2021-11-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_description_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='part',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
