# Generated by Django 3.2.8 on 2021-11-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
