# Generated by Django 3.2.8 on 2021-11-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20211126_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ausleihtage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
