# Generated by Django 3.2.8 on 2021-11-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20211123_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isavailable',
            field=models.BooleanField(default=True),
        ),
    ]
