# Generated by Django 3.2.8 on 2021-12-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20211204_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='preview',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
