# Generated by Django 3.2.8 on 2021-12-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_book_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='totalorders',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='preview',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
