# Generated by Django 3.2.8 on 2021-12-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_book_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description_small',
            field=models.TextField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='totalorders',
            field=models.IntegerField(default=0),
        ),
    ]
