# Generated by Django 3.2.8 on 2021-12-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20211208_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description_small',
        ),
    ]
