# Generated by Django 3.2.8 on 2021-12-08 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_book_description_small'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description_small',
        ),
    ]
