# Generated by Django 3.2.8 on 2021-12-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_remove_book_description_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description_small',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
