# Generated by Django 3.2.8 on 2021-11-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20211125_1940'),
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=45)),
                ('books', models.ManyToManyField(to='books.Book')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
