# Generated by Django 3.2.8 on 2021-11-23 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
