# Generated by Django 3.2.8 on 2021-12-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211125_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
    ]
